using UnityEngine;
using System.Collections;

public enum SpeechRecognizerError{
	ERROR_NETWORK_TIMEOUT = 1,
	ERROR_NETWORK = 2,
	ERROR_AUDIO = 3,
	ERROR_SERVER = 4,
	ERROR_CLIENT = 5,
	ERROR_SPEECH_TIMEOUT = 6,
	ERROR_NO_MATCH = 7,
	ERROR_RECOGNIZER_BUSY = 8,
	ERROR_INSUFFICIENT_PERMISSIONS = 9
}
